config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about_us', to: 'pages#about', as: 'about'

  get 'lizards/:number', to: 'pages#lizards', as: 'lizards', number: /\d+/

  get 'characters', to: 'characters#index', as: 'characters'

  get 'characters/:id', to: 'characters#member', as: 'character', number: /\d+/

  root to: 'pages#home', as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, :location, presence: true
  validates :name, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.order(:id)
  end

  def member
    @character = Character.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end

  def lizards
    @lizards = params[:number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/_character.html.erb
<div class="character">
  <h2>
    <% if display_student_link %>
      <%= link_to character.name, character_path(character) %>
    <% else %>
      <%= character.name %>
    <% end %>
  </h2>
  <h3>Location: <%= character.location %></h3>

</div>

app/views/characters/index.html.erb
<h1>Characters</h1>
<%= render partial: 'character',
           collection: @characters,
           locals: { display_student_link: true } %>

app/views/characters/member.html.erb
<%= render partial: 'character',
           object: @character,
           locals: { display_student_link: false } %>

<p><%= link_to 'Back', characters_path %></p>

app/views/common/_menu.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'Home', home_path %></li>
      <li><%= link_to 'About', about_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge45</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/menu' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim et nisl condimentum finibus. Duis egestas rutrum aliquam. Donec cursus at mi vitae scelerisque. Donec ullamcorper pretium scelerisque. Duis eu ultrices diam. Nullam dui ligula, dapibus facilisis fermentum nec, scelerisque at metus. Morbi ornare urna risus, eu sodales lacus pharetra eu. Praesent mollis imperdiet ornare. Integer pharetra, odio ac porta semper, lacus eros commodo tellus, sit amet sodales turpis quam eget est. Nunc sodales laoreet sodales. Donec feugiat venenatis commodo. Nam pulvinar ligula vitae lorem rutrum, pretium venenatis augue facilisis. Aliquam fermentum velit nibh. Ut risus erat, condimentum sit amet aliquet eget, blandit vitae nunc. Curabitur rutrum vehicula tempor.</p>

<p>Morbi bibendum porta orci, quis posuere ex consectetur at. Sed at est sit amet velit eleifend sagittis. Morbi elementum nulla nec ipsum laoreet, sed pharetra nunc porta. Fusce molestie, ligula non iaculis aliquam, enim eros dapibus lacus, mollis euismod nibh metus vel enim. Suspendisse ultrices est ex, eget convallis ex elementum vel. Ut lobortis sem tincidunt fermentum vestibulum. Phasellus dictum urna et magna laoreet fermentum. Quisque tempor massa purus, eu lacinia mauris convallis nec. Morbi vestibulum lectus sed libero pharetra rhoncus.</p>

app/views/pages/home.html.erb
<h2>Home</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim et nisl condimentum finibus. Duis egestas rutrum aliquam. Donec cursus at mi vitae scelerisque. Donec ullamcorper pretium scelerisque. Duis eu ultrices diam. Nullam dui ligula, dapibus facilisis fermentum nec, scelerisque at metus. Morbi ornare urna risus, eu sodales lacus pharetra eu. Praesent mollis imperdiet ornare. Integer pharetra, odio ac porta semper, lacus eros commodo tellus, sit amet sodales turpis quam eget est. Nunc sodales laoreet sodales. Donec feugiat venenatis commodo. Nam pulvinar ligula vitae lorem rutrum, pretium venenatis augue facilisis. Aliquam fermentum velit nibh. Ut risus erat, condimentum sit amet aliquet eget, blandit vitae nunc. Curabitur rutrum vehicula tempor.</p>

app/views/pages/lizards.html.erb
<h1>Lizards</h1>
<% @lizards.times do %>
  <p>🦎</p>
<% end %>